### ISSUE TITLE
SyntaxError: invalid syntax in df = pd.read_csv(f'./bitcoin-historical-data/{filename}.csv')

### ISSUE THREAD

**Issue by forhonourlx** [lefnire/tforce_btc_trader#12]
File "kaggle.py", line 30
    df = pd.read_csv(f'./bitcoin-historical-data/{filename}.csv')
                                                               ^
SyntaxError: invalid syntax

Could somebody give me a hand? Thanks.

**Comment by lefnire** [comment]
You on python 3.6+? New template string syntax. If not, install Anaconda, create a virtual env for 3.6 to use with this project.

**Comment by forhonourlx** [comment]
Understood. I was on python3.5. Anaconda then. Thank you.
