### ISSUE TITLE
from data.data import engine ModuleNotFoundError: No module named 'data'

### ISSUE THREAD

**Issue by forhonourlx** [lefnire/tforce_btc_trader#13]
Traceback (most recent call last):
  File "kaggle.py", line 7, in <module>
    from data.data import engine
ModuleNotFoundError: No module named 'data'

Could some body help? Thanks.

**Comment by forhonourlx** [comment]
Traceback (most recent call last):
  File "kaggle.py", line 8, in <module>
    from data.data import engine
ModuleNotFoundError: No module named 'data.data'; 'data' is not a package

**Comment by lefnire** [comment]
Dupe of #8. Pending commends on the PR
