### ISSUE TITLE
Error: Cannot find module 'webpack'

### ISSUE THREAD

**Issue by Hir0fumi** [lefnire/tforce_btc_trader#24]
It shows error while trying "5. Visualize".
What could be the cause of this (issue/problem)?
 Appreciate your help.
("npm install;npm install -g webpack-dev-server"comand has NO ERROR)

npm start => localhost:8080
module.js:478
    throw err;
    ^

Error: Cannot find module 'webpack'
    at Function.Module._resolveFilename (module.js:476:15)
    at Function.Module._load (module.js:424:25)
    at Module.require (module.js:504:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/usr/lib/node_modules/webpack-dev-server/lib/Server.js:22:17)
    at Module._compile (module.js:577:32)
    at Object.Module._extensions..js (module.js:586:10)
    at Module.load (module.js:494:32)
    at tryModuleLoad (module.js:453:12)
    at Function.Module._load (module.js:445:3)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! client@1.0.0 start: `webpack-dev-server "="`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the client@1.0.0 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

log
0 info it worked if it ends with ok
1 verbose cli [ '/usr/bin/node', '/usr/bin/npm', 'start', '=' ]
2 info using npm@5.7.1
3 info using node@v6.13.1
4 verbose run-script [ 'prestart', 'start', 'poststart' ]
5 info lifecycle client@1.0.0~prestart: client@1.0.0
6 info lifecycle client@1.0.0~start: client@1.0.0
7 verbose lifecycle client@1.0.0~start: unsafe-perm in lifecycle true
8 verbose lifecycle client@1.0.0~start: PATH: /usr/lib/node_modules/npm/node_modules/npm-lifecycle/node-gyp-bin:/home/ubuntu/tforce_btc_trader/visualize/client/node_modules/.bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/snap/bin
9 verbose lifecycle client@1.0.0~start: CWD: /home/ubuntu/tforce_btc_trader/visualize/client
10 silly lifecycle client@1.0.0~start: Args: [ '-c', 'webpack-dev-server "="' ]
11 silly lifecycle client@1.0.0~start: Returned: code: 1  signal: null
12 info lifecycle client@1.0.0~start: Failed to exec start script
13 verbose stack Error: client@1.0.0 start: `webpack-dev-server "="`
13 verbose stack Exit status 1
13 verbose stack     at EventEmitter.<anonymous> (/usr/lib/node_modules/npm/node_modules/npm-lifecycle/index.js:285:16)
13 verbose stack     at emitTwo (events.js:106:13)
13 verbose stack     at EventEmitter.emit (events.js:191:7)
13 verbose stack     at ChildProcess.<anonymous> (/usr/lib/node_modules/npm/node_modules/npm-lifecycle/lib/spawn.js:55:14)
13 verbose stack     at emitTwo (events.js:106:13)
13 verbose stack     at ChildProcess.emit (events.js:191:7)
13 verbose stack     at maybeClose (internal/child_process.js:920:16)
13 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:230:5)
14 verbose pkgid client@1.0.0
15 verbose cwd /home/ubuntu/tforce_btc_trader/visualize/client
16 verbose Linux 4.4.0-1052-aws
17 verbose argv "/usr/bin/node" "/usr/bin/npm" "start" "="
18 verbose node v6.13.1
19 verbose npm  v5.7.1
20 error code ELIFECYCLE
21 error errno 1
22 error client@1.0.0 start: `webpack-dev-server "="`
22 error Exit status 1
23 error Failed at the client@1.0.0 start script.
23 error This is probably not a problem with npm. There is likely additional logging output above.
24 verbose exit [ 1, true ]

**Comment by srozov** [comment]
@Hir0fumi can you share how you solved this issue?

**Comment by lefnire** [comment]
try `npm install --global webpack`  or w/o `--global`

**Comment by srozov** [comment]
Thanks! It's working now, after I tried `yarn add webpack-dev-server@^2.11.1`
