### ISSUE TITLE
kaggle.py: "ModuleNotFoundError: No module named 'data'"

### ISSUE THREAD

**Issue by moezzie** [lefnire/tforce_btc_trader#8]
Hey,

I'm trying to set the project up and am running into a problem when populating the data.

When running `python data/populate/kaggle.py` as described as part of step 2 I'm seeing this error message.
```
$ python data/populate/kaggle.py

Traceback (most recent call last):
  File "data/populate/kaggle.py", line 7, in <module>
    from data.data import engine
ModuleNotFoundError: No module named 'data'
```

My first guess was that it had to have something to do with the working directory. So i tried some different ones, but still can't get it to work.

Any of you guys having the same issue?

Cheers

**Comment by phibenz** [comment]
Hello,
I had the same problem, you can resolve it by prepending ]
`import sys, os   
sys.path.append(os.getswd())`

Regards

**Comment by lefnire** [comment]
Can y'all try now, with https://github.com/lefnire/tforce_btc_trader/pull/9 merged?

**Comment by forhonourlx** [comment]
It still does not work. "ModuleNotFoundError: No module named 'data'"

**Comment by TalhaAsmal** [comment]
@lefnire @forhonourlx  #14 should fix this issue on Windows

**Comment by lefnire** [comment]
@forhonourlx could you try now with #14 merged?

**Comment by lefnire** [comment]
just set it up on a new box & it worked, ya'll'll have to pull from master to get #14

**Comment by alirezaseifi** [comment]
I still have this issue 
```
Traceback (most recent call last):
  File "data/populate/kaggle.py", line 10, in <module>
    from data.data import engine
ModuleNotFoundError: No module named 'data.data'
```

**Comment by lefnire** [comment]
@alirezaseifi what happens if you run `PYTHONPATH=. python data/populate/kaggle.py`

**Comment by alirezaseifi** [comment]
Nice! it worked! you're awesome!

**Comment by lordvikas** [comment]
PYTHONPATH=. python data/populate/kaggle.py

What does this do?

**Comment by alirezaseifi** [comment]
@lordvikas PYTHONPATH arugment the default search path for module files. The format is the same as the shell’s PATH: one or more directory pathnames separated by os.pathsep
